backend:
  name: github
  repo: hampusfredrik/blogg
  branch: main
  auth_type: implicit
  auth_endpoint: https://blogg-brown-two.vercel.app/auth.html

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: https://blogg-brown-two.vercel.app
display_url: https://blogg-brown-two.vercel.app

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
