backend:
  name: github
  repo: hampusfredrik/blogg
  branch: main
  base_url: https://blogg-brown-two.vercel.app

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: uploadcare

site_url: https://blogg-brown-two.vercel.app
display_url: https://blogg-brown-two.vercel.app

locale: "en"

editor:
  preview: false

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: []}
    format: "frontmatter"
    frontmatter_delimiter: "---"
